"""Legacy code analyzer (P13) — the "โค้ดเดิม" input for faithful regeneration.

The DB manifest gives tables/columns; to rebuild a working replacement the AI also
needs the legacy application's structure: pages, CRUD flows, roles, and which
tables each page touches. This reads a source folder and builds a **code map**
(markdown) — WITHOUT storing the raw code and with secrets (DB credentials, API
keys) detected and excluded. The map enriches the regeneration brief.
"""
from __future__ import annotations

import os
import re
from collections import defaultdict
from dataclasses import dataclass, field

# operation suffixes seen in classic PHP CRUD apps
_OPS = [
    ("_report", "report"), ("_detail", "detail"), ("_edit", "edit"),
    ("_add", "add"), ("_del", "delete"), ("_search", "search"),
    ("_p", "print"), ("_email", "email"), ("_confirm", "confirm"),
]
# secret patterns — values are NEVER captured/stored, only the fact + file
_SECRETS = [
    ("db-credential", re.compile(r"mysqli?_connect|new\s+mysqli|PDO\s*\(", re.I)),
    ("password", re.compile(r"(pass(word)?|passwd|pwd)\s*[=:]\s*['\"][^'\"]+['\"]", re.I)),
    ("api-key", re.compile(r"(nvapi-|sk-[A-Za-z0-9]{10,}|AKIA[0-9A-Z]{12,}|xox[baprs]-)", )),
    ("define-secret", re.compile(r"define\s*\(\s*['\"](DB_PASS|DB_USER|DB_HOST|SECRET|API_KEY)", re.I)),
]
def project_map_path(project_id: int) -> str:
    """Where a project's legacy code map is stored (derived, no raw code)."""
    from .pipeline import _artifact_root
    d = os.path.join(str(_artifact_root()), "_projects", str(project_id))
    os.makedirs(d, exist_ok=True)
    return os.path.join(d, "code_map.md")


def read_project_map(project_id: int) -> str | None:
    p = project_map_path(project_id)
    if os.path.isfile(p):
        with open(p, encoding="utf-8") as f:
            return f.read()
    return None


_SQL_TABLE = re.compile(r"\b(?:FROM|INTO|UPDATE|JOIN)\s+[`'\"]?(\w+)", re.I)
_FORM_ACTION = re.compile(r"""action\s*=\s*['"]([^'"]+)['"]""", re.I)
_CODE_EXT = {".php", ".py", ".js", ".ts", ".jsp", ".asp", ".aspx", ".rb", ".java"}


@dataclass
class CodeReport:
    root: str
    files: int = 0
    modules: dict = field(default_factory=dict)          # module -> [ops]
    tables_referenced: list = field(default_factory=list)
    roles: list = field(default_factory=list)
    secrets: list = field(default_factory=list)          # [{file, kind}]
    code_map_md: str = ""

    def as_dict(self) -> dict:
        return {
            "root": self.root, "files": self.files,
            "modules": {m: sorted(set(ops)) for m, ops in self.modules.items()},
            "tables_referenced": sorted(set(self.tables_referenced)),
            "roles": sorted(set(self.roles)),
            "secrets": self.secrets,
            "secret_count": len(self.secrets),
        }


def _module_and_op(fname: str) -> tuple[str, str | None]:
    stem = re.sub(r"\.\w+$", "", fname)
    op = next((label for suf, label in _OPS if suf in stem), None)
    # module = leading alpha run (sale2 -> sale, superviser3 -> superviser)
    m = re.match(r"([a-zA-Z]+)", stem)
    return (m.group(1) if m else stem), op


def analyze(root: str) -> CodeReport:
    root = root.rstrip("/")
    rep = CodeReport(root=root)
    modules: dict[str, list[str]] = defaultdict(list)
    tables: set[str] = set()
    roles: set[str] = set()

    for dirpath, _dirs, files in os.walk(root):
        for fn in files:
            ext = os.path.splitext(fn)[1].lower()
            if ext not in _CODE_EXT:
                continue
            rep.files += 1
            module, op = _module_and_op(fn)
            if module == "left":     # nav include reveals a role
                roles.add(re.sub(r"^left_?", "", re.sub(r"\.\w+$", "", fn)) or "?")
            else:
                modules[module].append(op or "page")

            path = os.path.join(dirpath, fn)
            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    text = f.read()
            except Exception:
                continue
            for tbl in _SQL_TABLE.findall(text):
                tables.add(tbl)
            for kind, pat in _SECRETS:
                if pat.search(text):
                    rep.secrets.append({"file": fn, "kind": kind})
                    break   # one flag per file is enough

    rep.modules = dict(modules)
    rep.tables_referenced = sorted(tables)
    rep.roles = sorted(roles)

    # build the map markdown (no raw code — structure only)
    lines = [
        f"# Legacy code map — {os.path.basename(root)}",
        "",
        "> Generated by IVS Project Analyzer. Raw code NOT stored; secrets excluded.",
        f"> {rep.files} source files · {len(rep.modules)} modules · "
        f"{len(rep.tables_referenced)} tables referenced · "
        f"{len(rep.secrets)} files with secrets (excluded).",
        "",
        "## Modules (page → operations)",
        "",
    ]
    for mod in sorted(rep.modules):
        ops = ", ".join(sorted(set(rep.modules[mod])))
        lines.append(f"- **{mod}** — {ops}")
    lines += ["", "## Roles (from nav includes)", "", ", ".join(rep.roles) or "—",
              "", "## Tables referenced by the code", "",
              ", ".join(rep.tables_referenced) or "—", ""]
    if rep.secrets:
        lines += ["## ⚠️ Secrets detected (excluded from output)", ""]
        for s in rep.secrets:
            lines.append(f"- `{s['file']}` — {s['kind']}")
        lines.append("")
    rep.code_map_md = "\n".join(lines)
    return rep
