"""Transform a Structure into OpenCLI artifacts: cli-manifest.json + structure.md.

Manifest schema follows jackwener/opencli (site/name/access/strategy/args/columns/…).
PII columns are removed here per the chosen profile so no PII reaches the artifacts.
"""
from __future__ import annotations

import json

from app.services import pii_anonymizer
from app.models import OpenCliPiiProfile

from .connectors.base import Column, Entity, Structure


def _visible_columns(entity: Entity, profile: OpenCliPiiProfile) -> list[Column]:
    """EXCLUDE drops PII columns entirely; ANONYMIZE keeps them (values redacted
    at stream time). Manifest `columns` reflects what an agent will actually see."""
    if profile == OpenCliPiiProfile.EXCLUDE:
        return [c for c in entity.columns if not c.is_pii]
    return entity.columns


def build_manifest(structure: Structure, profile: OpenCliPiiProfile) -> list[dict]:
    manifest: list[dict] = []
    for ent in structure.entities:
        cols = _visible_columns(ent, profile)
        manifest.append({
            "site": structure.site,
            "name": ent.name,
            "access": ent.access,
            "domain": "internal",
            "strategy": "local",
            "browser": False,
            "args": [
                {"name": "limit", "type": "int", "default": 100,
                 "required": False, "help": "max rows to return"},
            ],
            "columns": [c.name for c in cols],
            "type": "js",
            "modulePath": f"./commands/{ent.name}.js",
            "sourceFile": ent.source_ref,
        })
    return manifest


def anonymize_value(value):
    """ANONYMIZE profile: redact a single cell value via the shared anonymizer."""
    if value is None:
        return None
    return pii_anonymizer.anonymize(str(value))


def build_structure_md(structure: Structure, profile: OpenCliPiiProfile) -> str:
    lines = [
        f"# {structure.site} — structure",
        "",
        "> Generated by IVS OpenCLI Bridge. Source read-only; raw data not stored.",
        f"> PII profile: **{profile.value}**",
        "",
        f"## Entities ({len(structure.entities)})",
        "",
    ]
    for ent in structure.entities:
        visible = _visible_columns(ent, profile)
        dropped = [c.name for c in ent.columns if c not in visible]
        lines.append(f"### `{ent.name}`  ({ent.source_ref}, access: {ent.access})")
        lines.append("")
        lines.append("| column | type | pii |")
        lines.append("|--------|------|-----|")
        for c in visible:
            lines.append(f"| {c.name} | {c.type} | {'yes' if c.is_pii else '—'} |")
        lines.append("")
        if dropped:
            lines.append(f"_PII columns excluded: {', '.join(dropped)}_")
            lines.append("")
    return "\n".join(lines)


def manifest_json(manifest: list[dict]) -> str:
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
